### ISSUE TITLE
Listening to Multiple Streams with a single streamer:listen command

### ISSUE THREAD

**Issue by aibarra11** [prwnr/laravel-streamer#16]
using the php artisan command:

```
php artisan streamer:listen district.updated
```

works fine, as i have my streamer.php config file configured:

````
    'listen_and_fire' => [
        'district.updated' => [
            \App\Listeners\DistrictUpdatedListener::class
        ],
        'city.created' => [
            \App\Listeners\CityCreatedListener::class
        ]
    ],
````

how would i listen to those different streams using a single php artisan streamer:listen command?

i saw the docs for adding listeners, but nothing for actually listening to different streams at the same time.

thanks

**Comment by prwnr** [comment]
unfortunately it's not possible currently. at my company we are using supervisors to auto-start/restart listeners on each event, so it's less annoying. I am also devoting some time on writing a redis stream monitor in GoLang (plus my listener monitor/automatic starting), but it's rather not for production and is in early alpha state. 

I thought about introducing such multiple listeners command in this package some time ago, but as far as I remember I needed a way for async calls, as it would be either clunky and slow (as it would have to run through all streams listening once and moving to next when nothing pops up) or it could end up blocked on one stream due to multiple messages received. it would be then no longer asnynchrous. so in the end, it's hard topic. I would suggest going with supervisors for now to keep all listeners as separate ones to have asnynchrousness of the streaming.

**Comment by aibarra11** [comment]
ah ok thanks. i was briefly considering letting kubernetes manage multiple instances of these, since i'm running this in docker, but that would get out of hand pretty quickly. I have about 20 streams to listen to for this one service. maybe a combination of configuration automation tools with k8's and rancher (we're using to manage k8s) might make it feasible. 

i'll go with the supervisor route for now. thanks

**Comment by prwnr** [comment]
I will devote some time to see if I can introduce at least some basic multi-listeners functionality (probably with XREAD in multiple streams manner), but hard to say how reliable it will be and how it will be preforming. Im here mostly concerned about that mentioned case of one stream producing multiple messages, so it will have to handle each one and that means that other streams listeners will have to wait for their time. in a small application with low traffic it would be rather ok, but with a lot of messages it could end up as a bottleneck (and this is not good especially when streams are rather not depending on each other and they could be handled at the same time asynchronously)

**Comment by aibarra11** [comment]
The supervisor approach actually works pretty well. Just tested it with 2 streams and handled it nicely. As a nice bonus, the auto-restarting takes care of an intermittent network. For some reason, running all this via docker-compose for local development results in random disconnections that i'm not seeing on our k8s test environment.
