### ISSUE TITLE
Speed of event?

### ISSUE THREAD

**Issue by EntonoX** [prwnr/laravel-streamer#37]
First of all compliments for this great package!

My question is about the handling speed of the streamer:listen command. Whenever i publish a message on a stream how fast will the streamer:listen pickup this message? is it (near) realtime? or does this involve the 'read_sleep' settings so in worst-case scenario it would take 1 sec. ?

**Comment by prwnr** [comment]
here is the final code responsible for listening: 
```php
private function listenOn(Waitable $on, callable $handler): void
    {
        $start = microtime(true) * 1000;
        $lastSeenId = $this->startFrom ?? $on->getNewEntriesKey();
        while (!$this->canceled) {
            $this->inLoop = true;
            $payload = $on->await($lastSeenId, $this->readTimeout);
            if (!$payload) {
                if ($on->getNewEntriesKey() === Stream\Consumer::NEW_ENTRIES) {
                    $lastSeenId = $on->getNewEntriesKey();
                }
                sleep($this->readSleep);
                if ($this->shouldStop($start)) {
                    break;
                }
                continue;
            }

            $lastSeenId = $this->processPayload($payload, $on, $handler);
            $lastSeenId = $lastSeenId ?: $on->getNewEntriesKey();
            $start = microtime(true) * 1000;
        }
    }
```

so if talking about response time, it depends on the Redis, because my code calls the blocking await on stream, simply waiting for something pop up from stream.

the read sleep option is there in case, when the await reaches its timeout or breaks out of the "waiting" by any other reason, returning empty payload. then the code sleeps for the given time to give the stream some rest and attempts to listen again. 

so in the end, in the worst case scenario it may be that 1s (depends on read sleep configuration), but in general, if listener is not processing anything and there was no timeout, then it's up to Redis response time. 

hopefully explained this well given that I remember this part good enough.

**Comment by EntonoX** [comment]
Thanks for the explanation! This can be closed :)
