### ISSUE TITLE
Multiple listeners

### ISSUE THREAD

**Issue by Debiano** [prwnr/laravel-streamer#43]
Hello,

thank you first for this great project. Its very nice to make communication between 2 laravel projects possible.

Does the project have a listener that we can run that watch for all events specified in the ListenerStack? At the moment i just found the command streamer:listen which needs the event parameter. Of there is no option to do that, what is the best way to listen to maybe 10 events? 

Best regards

**Comment by prwnr** [comment]
Hi @Debiano ,

Unfortunately at this point it has not. 
Currently the only way to run 10 listeners is to actually run those 10 in separate processes. 

But I do have in plans adding a single command for multiple streams, as your request is not the first one. However I dont have that much time now due to family stuff, so it may not be soon (but seeing another request may speed this up). 

The other way to do this now (if you need it sooner) is to write a semi-functioning command by your own. I did something like this for my work project, but I cant move that code into the package as the package code needs to be more flexible and generic, where at work I just simply wrote it to work for our specific use case. 

I will try to devote my free time in the upcoming weeks/month and see if I can manage adding the multiple streams listen command to the package. 

Regards

**Comment by Debiano** [comment]
Hey @prwnr ,
thank you for your answer!

I'm curious, but family comes first - i will try to write a semi-function command as you said for now. Thank you for your great work, the package is a really good idea. 

Best regards

**Comment by prwnr** [comment]
@Debiano 

what I can help now is to suggest:
1. write a class that will wrap around the `$result = $this->redis()->xReadGroup($group, $consumer, $this->streams, null, $timeout);` call as it will read multiple streams. 
2a. this->redis() is from `ConnectsWithRedis` trait
2b. consider creating group on each stream you want to listen, to maintain the consumer - group acknowledge
2c. the `$this->streams` should be an array of `"stream name" => ">"` 
3. the result of the read group will be an array of streams with each one as array of messages - that is because it may return result for multiple streams, the format:
```php
Array
(
    [stream_name] => Array
        (
            [1541670150555-0] => Array
                (
                    [message] => content
                )
        )
)
``` 
4. here you have two cases of how to deal with this format:
4a. you dont care about the order - so you do nothing
4b. you care about the order (order of when message was sent) - so you need to re-format the array, so that the IDs (timestamps) will be sorted in the order from smallest to biggest (this is how I will implement this)
5. you need to call the class and method with the point 1. calls somewhere in your Command making it loop endlessly (while (true), so the xReadGroup will pop up messages for you to trigger listeners
6. consider calling `acknowledge` on the messages, to dont get them processed again with your command restarted (but that requires you to create groups that I mentioned in 2b) 
7. remember that here you will receive plain message format and you need to decode it by yourself (from a JSON). you mostly care only about what is inside `data` field of the message. 

briefly what I can help you now with.

**Comment by beeyev** [comment]
I just wanted to say, thanks for such a great tool, it's really useful. And I would like to join the proposal to implement this feature.
Hope you will find some time, I believe this tool has a great potential.

**Comment by prwnr** [comment]
@beeyev glad to see you appreciate this package.
seeing another request for this feature, I will try to start working on it this month and will see the outcome. The workaround is working as Debiano confirmed, but I cant just put it into the package, cause it would be a breaking change like that, I need to find a way to make it a minor release, so this is my main concern for how long it may take to implement this.

**Comment by beeyev** [comment]
Glad to hear that. 
> but I cant just put it into the package, cause it would be a breaking change  

Why don't you just create a new major version? Of course, it could break backwards compatibility, but it's normal. Major features sometimes require a lot of changes.

**Comment by prwnr** [comment]
> Glad to hear that.
> 
> > but I cant just put it into the package, cause it would be a breaking change
> 
> Why don't you just create a new major version? Of course, it could break backwards compatibility, but it's normal. Major features sometimes require a lot of changes.

cause I have in plans min PHP version bump right after and I would like to get this multi-stream feature included in the old one and in the new one, not jumping two major version in a short time.

**Comment by francoisauclair911** [comment]
+1 from my side, very much interested in such feature. Thanks for the hard work

**Comment by prwnr** [comment]
@francoisauclair911 @beeyev @Debiano 
so, I did some work on this in the related PR. its stable I think, but I will have to check some more things still and I wont be able to do that for next few days. read the comment in PR for a short information of what is changed and how to use this new multi-stream option. 

would appreciate if you could test this out on your sides and see if it works as you would expect and that it does not break anything (I did my changes keeping up all the old interfaces as is, to dont cause a major version bump).

**Comment by francoisauclair911** [comment]
@prwnr  Will do

**Comment by prwnr** [comment]
merging multi-stream listening to master. will tag this with a beta tag for now
