### ISSUE TITLE
Undefined type 'Redis'

### ISSUE THREAD

**Issue by renteriadev** [prwnr/laravel-streamer#48]
In a couple of days ago I've been trying to use your package (cause if looks so useful for what I need) bur I've been getting a couple of errors that I do not know how to solve it.. The main one that is bothering me is this:

 _Class "Redis" not found

  _at vendor/prwnr/laravel-streamer/src/Concerns/ConnectsWithRedis.php:24
    {
    $connectionName = config('streamer.redis_connection');
   $connection = Redis::connection($connectionName ?? 'default');
  $connection->setOption(\Redis::OPT_PREFIX, '');
     return $connection;
  }
}

      +20 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()__

I've tried to install Redis but I got the same error. It's likes it can't find that package or I do not know...
Hope you can help me with this and sorry for my english

**Comment by renteriadev** [comment]
Thanks a lot for replying me intermediately!!!! i will check what you told me!!!

**Comment by renteriadev** [comment]
hi @prwnr 
i did what you told me yesterday (it worked to use your package) but now (and i dont know why) looks like Redis does not have this constant OPT_PREFIX and i got this message many times "Undefined class constant 'OPT_PREFIX'." so I dont know if im missing something or what.. Ive been googling but without success.. hope you can help me with this.

oh this happen when im going to run this command "php artisan stream:listen chat.streamer.event"

**Comment by prwnr** [comment]
@renteriadev Im not quite sure why you are getting that error, because I can clearly see this constant on my local PC
![image](https://user-images.githubusercontent.com/11226976/192803932-fbbffbca-0dd6-42a0-8b49-3f2ca498a598.png)
and I also see that the phpredis documentation shows examples of usage of that field: https://github.com/phpredis/phpredis#examples-34 

maybe you got the wrong version of the phpredis package? or some nasty cache? doesnt really look like something my package is causing, because the latest tests would fail on this.

**Comment by renteriadev** [comment]
Im using laravel sail so i dont know if it's related about what mentioned you previously... im gonna check the link! thanks once again!

**Comment by prwnr** [comment]
I never tested nor used this with Laravel Sail, so here I cant help if it affects this package in any way. But I would easily assume, that it still something with the phpredis, because it does not see a constant that is there inside the class (have you tried viewing the class? or its on remote server and you cant?)

**Comment by renteriadev** [comment]
not.. i havent tried what you said but not sure if im using the correct "export"
 i do this "use Illuminate\Support\Facades\Redis;" so maybe im exporting the wrong class

**Comment by prwnr** [comment]
> not.. i havent tried what you said but not sure if im using the correct "export"
> i do this "use Illuminate\Support\Facades\Redis;" so maybe im exporting the wrong class

this one is clearly wrong.
the `Redis` here is the PHPLib class.
so it should go with `\Redis` - nothing more :)

**Comment by renteriadev** [comment]
> > not.. i havent tried what you said but not sure if im using the correct "export"
> > i do this "use Illuminate\Support\Facades\Redis;" so maybe im exporting the wrong class
> 
> this one is clearly wrong. the `Redis` here is the PHPLib class. so it should go with `\Redis` - nothing more :)

hi!! sorry for replying you too late but you not going to believe XD
what you recommend me yesterday didnt wortk XD
once again it seems like it does not want to recognize where is the Redis class or something like that not sure what's happening on my project
thanks for your time and help man :)
