### ISSUE TITLE
Performance vs laravel horizon

### ISSUE THREAD

**Issue by fannyfan414** [prwnr/laravel-streamer#52]
Hello! Is this queue system faster than laravel horizon? Horizon uses lpush,lpop redis commands.
And another question - can I specify the number of workers that will process tasks (listen for new stream events) in parallel as laravel horizon?

**Comment by prwnr** [comment]
ah those Github notifications, my apologies @fannyfan414 but I didnt see this until now. 

I wouldn't compare this to Laravel Horizon, because this is not Redis Queue system, but Redis Streams - therefore the use cases may differ a lot - and I dont have any speed comparison to show for you unfortunately.

as per second question - you can listen to an even from multiple processes, with the use of `group` and `consumer` flags you can achieve a parallel listeners. 
the use case would be like:
First worker:
```
php artisan streamer:listen some.event.name --group=foobar --consumer=foo
```
Second worker:
```
php artisan streamer:listen some.event.name --group=foobar --consumer=bar
```

So, notice here that both processes are listening to the same event and are in the same group (Redis Streams group), but they are both different consumers. This will make them listen in parallel, so that when one of the consumers is busy processing an event and new event comes in, the second consumer will pick it up in its place. 

This functionality comes from Redis Streams
