### ISSUE TITLE
Emitting event within queued job doesn't process the job

### ISSUE THREAD

**Issue by francoisauclair911** [prwnr/laravel-streamer#53]
Hi

I am faced with a weird issue.

I want to dispatch a laravel queued job to emit an event to the redis stream.
The job gets dispatched and the event gets emitted on the stream. 
The queue worker returns "done", however it doesn't delete the job from the queue.

The only workaround I found was to call 
`$this->delete()` PRIOR to calling this library. 
But then I need to setup a whole try/catch to basically recreate the whole worker retry logic.

Also adding `$this->delete()` after calling the `emit` method doesn't work.

Let me know what I can do to help

Francois

**Comment by prwnr** [comment]
My apologies for late response @francoisauclair911 

More information would be helpful for sure, cause it sounds kinda weird that triggering a `Stremer::emit` impacts Laravel's built in Queue functionality in a way that it fails to "delete" the job. 

What Laravel version are you using? 
What Redis version are you using?
What PhpRedis version are you using?

Is the Queue used on a Database or Redis? if the later, some more info may be needed to pin point the problem, perhaps using Queue on the same Redis server as Streamer is the culprit here, but I cannot tell cause in my production environment we are using DB for Queue ATM, so we never faced similar problem.
