### ISSUE TITLE
Duplicate consumer name when running two workers at the same time

### ISSUE THREAD

**Issue by MuhammedAlkhudiry** [prwnr/laravel-streamer#64]
Hello, thank you for this package,

We are running two workers without providing `--consumer` since we don't have access to the worker name that starts the `streamer:listen`

and the package currently uses `time()` when no consumer name is provided, what if the two workers started at the same time? 

because our two workers starts at the same time (and same group), which causes them to both process the same event, how can we solve this?

**Comment by prwnr** [comment]
@MuhammedAlkhudiry the `--consumer` is the solution to this problem. The behaviour that you are describing would be the same if you would run the XREAD command in two separate processes in Redis CLI - both processes would get the same message, because they don't claim ownership for it. 

To avoid this, Redis introduced the consumers that are not disturbing each other while processing messages from the Stream and are acknowledging the message once it's processed, to don't consume it twice if they get restarted.

Think of the XREAD like a simple event pub-sub - where every subscriber gets notified with the published message. While the XREAD with Consumer is here to make sure that only one (the first to come) subscriber gets the message. 

See more about this here: https://redis.io/docs/latest/develop/data-types/streams/#consumer-groups 

I don't think the package here should be trying to make a workaround for the case where no `--consumer` is used, as this is the expected behaviour on Redis side (unless there were some changes to Redis that I am not aware of as of now).

**Comment by MuhammedAlkhudiry** [comment]
Thanks for the reply. 
It seems the package currently uses `time()`when no consumer is provided, wouldn’t be safer if we used a random string? 

Alternatively and currently, I could solve my issue by passing random string `streamer:listen —consumer=${generate random string}` (is this a good idea?)

**Comment by prwnr** [comment]
@MuhammedAlkhudiry the thing is, that this is an "expected" behaviour - not using the consumer goes to `XREAD` Redis command under the hood, while with the consumer, it switches to `XREADGROUP`, which behaves differently. 

From what I checked in the code right now, I see that what you need to pass is the `--group` option actually, and the consumer will be generated for it (group + timestamp). 

So, if you have two workers running in parallel, you could give both the same `--group=myworkers` name, omitting the `--consumer` flag (if it's problematic to pass it). This will switch the listening to `XREADGROUP` and should fix the problem you are facing. 

Do note that if you want two consumers to process different messages, they need to be in the same group.

**Comment by MuhammedAlkhudiry** [comment]
Thanks for your explanation, currently I’m running them both with the same group, and since they start at the same time they will both have the same consumer, right?

and since they are both have the same group and consumer they may both access the event twice, is that correct? 

Thanks for your patience.

**Comment by prwnr** [comment]
@MuhammedAlkhudiry  you are right. In that case they indeed can consume the same event. I thought that you are not running with a group. I misunderstood. 

Given this, your suggestion to change this time ahead generation to a random string makes sense and I will try to devote some time to make it, as it's a quick on. However not sooner than tomorrow.

**Comment by MuhammedAlkhudiry** [comment]
Thank you @prwnr for your support

**Comment by prwnr** [comment]
@MuhammedAlkhudiry https://github.com/prwnr/laravel-streamer/releases/tag/4.2.0 should do the thing for you
